REQUIRED_DATASET_COLUMNS = [
    "record_id",
    "study_id",
    "sample_id",
    "product_category",
    "intended_use",
    "study_type",
    "test_purpose",
    "pathogen",
    "strain_info",
    "inoculation_type",
    "time_days",
    "storage_temperature_c",
    "temperature_profile_type",
    "ph",
    "aw",
    "salt_percent",
    "sugar_percent",
    "fat_percent",
    "preservative_flag",
    "preservative_type",
    "acidulant_type",
    "packaging_type",
    "oxygen_condition",
    "initial_inoculum_log_cfu_g",
    "observed_count_log_cfu_g",
    "study_final_exceeds_regulatory_threshold",
    "max_time_days",
]

REGRESSION_FEATURES = [
    "time_days",
    "storage_temperature_c",
    "ph",
    "aw",
    "salt_percent",
    "sugar_percent",
    "fat_percent",
    "initial_inoculum_log_cfu_g",
    "product_category",
    "intended_use",
    "study_type",
    "test_purpose",
    "pathogen",
    "strain_info",
    "inoculation_type",
    "temperature_profile_type",
    "preservative_flag",
    "preservative_type",
    "acidulant_type",
    "packaging_type",
    "oxygen_condition",
    "max_time_days",
]

CLASSIFIER_FEATURES = [
    "storage_temperature_c",
    "ph",
    "aw",
    "salt_percent",
    "sugar_percent",
    "fat_percent",
    "initial_inoculum_log_cfu_g",
    "product_category",
    "intended_use",
    "study_type",
    "test_purpose",
    "pathogen",
    "strain_info",
    "inoculation_type",
    "temperature_profile_type",
    "preservative_flag",
    "preservative_type",
    "acidulant_type",
    "packaging_type",
    "oxygen_condition",
    "max_time_days",
]

CATEGORICAL_FEATURES = [
    "product_category",
    "intended_use",
    "study_type",
    "test_purpose",
    "pathogen",
    "strain_info",
    "inoculation_type",
    "temperature_profile_type",
    "preservative_type",
    "acidulant_type",
    "packaging_type",
    "oxygen_condition",
]

LEAKAGE_COLUMNS = [
    "record_id",
    "study_id",
    "sample_id",
    "replicate_id",
    "product_id",
    "product_name",
    "timepoint_label",
    "temperature_profile_detail",
    "observed_count_value",
    "observed_count_numeric",
    "observed_count_operator",
    "observed_count_unit",
    "observed_count_log_cfu_g",
    "growth_observed",
    "delta_log_from_baseline",
    "exceeds_regulatory_threshold",
    "regulatory_threshold_value",
    "regulatory_threshold_unit",
    "data_source",
    "is_synthetic",
    "assumption_profile",
    "study_final_growth_observed",
    "study_final_exceeds_regulatory_threshold",
    "study_final_log_cfu_g",
    "dataset_split",
]

DEFAULT_SCENARIO_VALUES = {
    "intended_use": "ready_to_eat",
    "pathogen": "Listeria monocytogenes",
    "study_type": "challenge_test",
    "test_purpose": "shelf_life_validation",
    "strain_info": "2-strain cocktail",
    "temperature_profile_type": "constant",
    "max_time_days": 42,
}
